sudo: false
language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0

before_script:
    - composer self-update && composer install

script: ./tests/runTests.sh

after_script:
    - php vendor/bin/coveralls -v
